### PR TITLE
 Update parser for 5.0.8, protocol 86383

### PR DESCRIPTION
**Pull request by dermorz**
This PR introduces the new protocol. It is copy pasted from the previous one after seeing there was no diff between the previous 2 existing ones, so there might be some unknown/untested issues.

I found this library when looking for replay parsers to write my own progress measuring tool. When trying it locally, I figured out that it's not working as expected. When I then tried to use zephyrus.gg I noticed, it's also not parsing replays I suspected there to be a general problem after the season change and minor version bump on starcraft.

gg

### CODE REVIEW

**Comment by dermorz** [comment]
Not sure about the DeepSource Error. I think you enabled deepsource.io for this repo but never committed a `.deepsource.toml`.

**Comment by ZephyrBlu** [comment]
Hey! Thank you for bumping the version. I have neglected this library and zephyrus.gg lately :/.

Usually the previous protocol is the same as the new one, so there shouldn't be any issues there. DeepSource was a random thing I tried out a while back just to see what it was. The error doesn't mean anything.

I guess you copied the ability, unit, etc data into new files? I usually regenerate the data using sc2reader because it can change between game versions even if the protocol is the same.

Tomorrow I will regenerate the game data, add it to the PR then merge it and cut a new release for the package on PIP. I'll also add instructions for regenerating game data to the readme.

**Comment by on4r** [comment]
Looking forward to this!

**Comment by on4r** [comment]
I'm having troubles to get this pull request to work locally. @dermorz can you please explain how you are testing this locally?

**Comment by ZephyrBlu** [comment]
Sorry I haven't followed through on regenerating the data and cutting a new version, I have been occupied with other things.

**Comment by ZephyrBlu** [comment]
I've been following these instructions then copying the new data into the parser and running the `generate_game_data.py` script (I think it's called that) to convert the CSV data into `zephyrus_sc2_parser` data.

https://github.com/ggtracker/sc2reader/blob/upstream/sc2reader/data/HOWTO.md

**Comment by dermorz** [comment]
> I'm having troubles to get this pull request to work locally. @dermorz can you please explain how you are testing this locally? 

I was testing it locally by installing my local branch with:

```
pip install -e .
```

And then having a tiny test script that reads a replay file of the current version and pretty prints out the parsed replay namedtuple as dictionary.

So no sophisticated testing, just checking if works what was not working with the current release.

**Comment by on4r** [comment]
Ah i didn't knew about the `-e` flag of pip. Thanks!  
Just got it working and tested it with some replays of the latest patch. No errors, everything working as expected.

**Comment by AndreasPK** [comment]
Hey I tried using this recently but decoding failed. I assume because of the new protocal. Would be great if this fix could be landed!

**Comment by ZephyrBlu** [comment]
I completely forgot about this :/. I added a change to the base unit cost data and [released version `0.3.7` on PyPi](https://pypi.org/project/zephyrus-sc2-parser/). I had to bump the version again because apparently I'd already released a `0.3.6`.

**Comment by AndreasPK** [comment]
Thanks!

**Pull request merged**
